services:
  postgres:
    image: postgres:16-alpine
    container_name: lms_alprodas_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lms_alprodas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alprodas@POSTGRES123
      TZ: Asia/Makassar
      PGTZ: Asia/Makassar
    command: >
      postgres
      -c timezone='Asia/Makassar'
      -c log_timezone='Asia/Makassar'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lms_alprodas_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: lms_alprodas-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3005:3000"
    env_file:
      - .env.production
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: lms_alprodas-migrator
    env_file:
      - .env.production
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed
      "
    depends_on:
      - postgres
    restart: "no"

  pgadmin:
    image: dpage/pgadmin4
    container_name: lms_alprodas_pgadmin
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
